services:
  django-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - SERVER_KEY=${SERVER_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
    ports:
      - "8000:8000"
    command: >
      sh -c "
      python manage.py migrate && 
      python manage.py collectstatic --noinput && 
      gunicorn -b 0.0.0.0:8000 myproject.wsgi:application
      "
    restart: always

volumes:
  db_data:
