# Generated by Django 5.0.3 on 2024-03-21 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('phone', models.CharField(max_length=13, verbose_name='phone_number')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('turkish_id_number', models.CharField(max_length=11, verbose_name='turkish_id_number')),
                ('password', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='password')),
            ],
        ),
    ]
