# Generated by Django 4.2.7 on 2024-06-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notification',
            field=models.BooleanField(default=False, verbose_name='email_notification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_notification',
            field=models.BooleanField(default=False, verbose_name='sms_notification'),
        ),
    ]
