# Generated by Django 4.2.7 on 2024-06-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_email_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='app_lang',
            field=models.CharField(default='tr', max_length=3, verbose_name='app_lang'),
        ),
    ]
