# Generated by Django 4.2.7 on 2024-12-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_customuser_device_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_new_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="phone_number"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="turkish_id_number",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="turkish_id_number"
            ),
        ),
    ]
