# Generated by Django 4.2.7 on 2025-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingaddress",
            name="alias",
            field=models.CharField(default="", max_length=50, verbose_name="alias"),
        ),
    ]
